### ISSUE TITLE
Leaks global variable WebAssembly

### ISSUE THREAD

**Issue by antony** [dcodeIO/webassembly#11]
It seems that this module causes a global variable leak 'WebAssembly'.

Perhaps this is required or intentional, but it breaks leak detection for all dependent packages (chalk, for example).

If it's possible, it'd be best to stop 'WebAssembly' leaking, if this isn't possible then feel free to close this issue.

**Comment by dcodeIO** [comment]
Erm, isn't [WebAssembly](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly) just a browser global nowadays?

**Comment by antony** [comment]
Possibly, but it isn't in nodejs, as far as I know.

**Comment by dcodeIO** [comment]
Since node v8

**Comment by nickzuber** [comment]
Running node `v6.11.1` (I'm guessing just v6+) you can expose wasm as a global.

```
$ node --expose-wasm
> Wasm
{ verifyModule: [Function],
  verifyFunction: [Function],
  instantiateModule: [Function],
  instantiateModuleFromAsm: [Function] }
```

**Comment by devsnek** [comment]
its been `WebAssembly` since it was removed from the flag
![](https://gc.gy/⚩.png)
