### ISSUE TITLE
EACCES from scripts/setup

### ISSUE THREAD

**Issue by devsnek** [dcodeIO/webassembly#14]
strange eacces on postinstall from scripts/setup
![](https://gc.gy/說➞.png)

**Comment by dcodeIO** [comment]
Seems to be similar to https://github.com/dcodeIO/webassembly/issues/13

**Comment by devsnek** [comment]
it never makes it past install so i can't chmod any tools or chown any directories because npm cleans up the failed install

**Comment by dcodeIO** [comment]
isn't there a switch for npm in this case?

**Comment by devsnek** [comment]
i thought it was `--unsafe-perms` but that didn't appear to work

EDIT: its `--unsafe-perm` and it appears to work now
