### ISSUE TITLE
malloc vs memory.grow

### ISSUE THREAD

**Issue by gillesboisson** [dcodeIO/webassembly#19]
Hi,
Awesome minimalist tool, all is working fine expect when I try to grow memory or use malloc. 

- When I use malloc it returns a pointer out of the buffer size. 
- When I use memory.grow I have detachedArray error on string conversion methods (executed when I uses console_log).

Do I have to grow memory at a specific time ?

I'm not a C expert maybe i'm doing something wrong. I working on mac and using npm lib using webpack to compile the final app.  

Otherwise all's fine I did some test on matrix operation using a custom C port of [gl-matrix](http://glmatrix.net/) I have a x10 execution speed with optimisation enabled. Performance is much less significant when I use math function (sin,cos) on matrix rotation), I have x1.3 exec speed.
 
Cheers,

**Comment by dcodeIO** [comment]
When growing the memory, the memory object on the JS side changes. It basically throws away the old buffer and makes a new, larger one with the same contents. Then, when accessing the old one, there's the error you are seeing.

There is [this little function](https://github.com/dcodeIO/webassembly/blob/master/src/index.js#L72) in the loader that should take care of it, but it must be called every time memory grows, for example by importing `void _grow()` and calling it.

**Comment by gillesboisson** [comment]
Thanks it works perfectly,
