### ISSUE TITLE
install fail 

### ISSUE THREAD

**Issue by izengliang** [dcodeIO/webassembly#2]
Downloading binaries for darwin-x64 ...

/private/tmp/w/node_modules/webassembly/scripts/setup.js:64
        throw err;
        ^

Error: no prebuilt binaries available for darwin-x64 (code 404)
    at RedirectableRequest.https.get.res (/private/tmp/w/node_modules/webassembly/scripts/setup.js:21:22)

**Comment by dcodeIO** [comment]
As the README states, there are no binaries for Mac, yet. Unfortunately, I don't have access to any system I could use for this task. Not sure if the linux binaries would work though.

Tools download thingy: https://github.com/dcodeIO/webassembly/releases
