### ISSUE TITLE
MacOS binaries

### ISSUE THREAD

**Issue by jnordberg** [dcodeIO/webassembly#4]
Had to comment out the `-static-libgcc` flags for it to compile. Test passing, haven't tried anything else yet.

https://johan-nordberg.com/tmp/tools-darwin-x64.tar.gz

**Comment by dcodeIO** [comment]
Cool, thanks! Just [added](https://github.com/dcodeIO/webassembly/releases/tag/0.10.0).

**Comment by jnordberg** [comment]
Cheers!
